base_wireguard_private_key: ENC[AES256_GCM,data:lDj1o19M90wWE1Q5RDajVGRN+fiCpbFSs6cw8QM4fk//SuC3jHGQmPjAUWk=,iv:mKZKeSMvguSZyVnaeLNd/k6s77cg1t3l3KpVuJI1yOA=,tag:8n7aRG+LlL8/tZJi0Lv2NQ==,type:str]
ansible_host: ENC[AES256_GCM,data:wYp6C09qG6ZEFIYoLH8=,iv:P3Ks1/HVgcO/Cn7rD43Dk3BtlqnWzgIp8qGMqalvWfU=,tag:6z9L81WlClx5BZwOtcsB+w==,type:str]
base_wireguard_ipv4: ENC[AES256_GCM,data:WrFP5M/UAu5t,iv:Zl3Mn4y6rYu/1kWEXl5umiZ6Wtl4/o4TomcVfSGcaw0=,tag:R+Atk5I1kOW8myBj8ZMbYw==,type:str]
base_wireguard_ipv6: ENC[AES256_GCM,data:0c/AKLMb+d609s5OzVv24M8=,iv:BsZwVs3cLAEZzcwjD0jU//FekiAaKbfqgK4X3Q7nE4Y=,tag:OQ9gPI+KMOhfR5oTPY2VPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZEhzUGxFUnBicnQraThO
            T2lxNEhLQkpCTDN5aGJhekxFZmZMTEJmUXpJCkxNQlBoUmdkVWtXSDNnL3VqRHM5
            Mk1ySVJYUVRTQ1phTkRKRjE4RDJoNlUKLS0tIG9DT3Q3Si9GcW85RHhiK3hFT1c4
            dXJLZERIeVdjWlpwY3BQRnRZRG9xNjAKPEpbFIfhQ1arPjfpYDZCj0BzwxOU5fXV
            J0OLo95Rs6YGJN/o6WfpH7avguFP8jj3dTJB4hmcBRizK+xACFgQNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WW51MktZYkZwWGxIWlpa
            TGdoR293VzQ3QUNaSlZZb1VLbkpsY0h3NW5ZCjJkeTFFTkZ1aVk1SldCSThXYytN
            NVk2YllnWjRsVkY5THI0UHprUCtvakUKLS0tIDh1bFhWbEVWVDczaEYzREZQd3Fs
            OVdETEtIMDUvU2MvSHlBVndzTnhaRk0KgNjVKWAp1o3M4eM5YmicNmDfWVcDwQ0z
            OxBRKpC7ZImRKb8wABiI9aW+7eyp+puVWGJSnpgPWqMPr4TFHvUefQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxhkt6syw8mmfzzzgf9dtjkvt5j7au36nnsmv4vvuejdwmpv9ftssv9vkq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SWZ0Rm1TdTk1NXpkeElF
            Q0JBei9XYVRkeEhDOVRZdkxwblJRMGF3bmtZCkd2b3JLcDRQTy9aS3BkVGVucFRY
            bFBNb2lhWnJpZkFzeXNncDVkODRIVUkKLS0tIDJQNWNibmpSUk5ZMTlNNjVVQ0VP
            ZHdBallMQ0MydzJLK3lhRkxJSG9jNjAKdK12PhsjKMt95Jxzn0wY/+TVQ1DsElWA
            AWUz9HkB5u1Kt6RTvtjBfOsAGXxst2g8H10z0hdRv3//Rqg01u1ikg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3ze7nymx9tk78r78mukpxjjuhhaxh2wqz2tpem9ymcgngr94f5qg434hl
    lastmodified: "2026-09-06T10:38:26Z"
    mac: ENC[AES256_GCM,data:ya7VFmbnkXdS3ZtlCcxEMBZfafJ0aUBF4HaExFLBr+MgPTabJEfeTZj4E4Qyi7rYMdNicHB/P2hbB2vE6N62CXyMe5FJFtlWs+GRXLcqRPSh0d/+joSc/dqy7P5uLNfbr66gkX4mtjWWQpLOud8QSgTcIFb3/IHuxQL5UqXTERw=,iv:32TJ4nXFPSfF0dThpiql8N7Izlke36gejMfqKTX/R4o=,tag:Kcv+C2RDWpZMB0yI9k7tUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
