base_wireguard_private_key: ENC[AES256_GCM,data:XLPWl7VpSW4y+4hKtupqwULYfw228JZi5cte2aqKv5zJPMjRJ3epZuW44nU=,iv:xcNR3jSfh77wBrWwq1nLAZio5n+LigaEBvWZ1Ar3mx0=,tag:HpKg2Sk4AEv0VduYxid9PQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SnBCN1N5cVhNSXRLWWZD
            MHB5VHp2WVRwVk9uTG5lNWIzWlI0OWg0bUh3CmE1ZURoQ3JVazl5NjkxN0VjQTFU
            TEFZaUFVa09yRXIxRHFwTHk3Y28xSDQKLS0tIG1sSTNWd0hVdlV4WDM5c3A1Zkpp
            ZEJnV0tORjFLeC91VEJYdW85Wk1xVVUKMSOiBE7lXaoEc1igB/OA6qVjD/Ws0gwR
            74wjMUeX9Bf+s29KVTLWeT0nc0exqwqMg5iQcsspK1zpnW2oY9mZ0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
    lastmodified: "2026-09-05T14:21:12Z"
    mac: ENC[AES256_GCM,data:a/LX7eGdwvhKUixCrwmhVyarPoYrsLx4kjfNUYIRK4UHF0JjcV6cTPHv+MRuCPyouyhdt4FN9zVNmqjpB0mXyQ7o+9CTvr7ghX8frOC1cYYOVOoMtc5y01Eoj32ib8cFXLkD8iIf5is1CGUcdK9wkazPjmMDjnKonQGk/JA0738=,iv:XkubrRiJYdRmShNKU0tjQInUEmCUeJPTLhzeBV77Acw=,tag:wMYEEKdedCpTnuMIRh1esQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
