base_wireguard_private_key: ENC[AES256_GCM,data:we7eAcI2cvK1,iv:f48snKgJWZngnRoLU4s7XGaXLfHw5x7/cbEoaBQkUPs=,tag:hL3wQe0dZngYhu5KxcU6sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SnBCN1N5cVhNSXRLWWZD
            MHB5VHp2WVRwVk9uTG5lNWIzWlI0OWg0bUh3CmE1ZURoQ3JVazl5NjkxN0VjQTFU
            TEFZaUFVa09yRXIxRHFwTHk3Y28xSDQKLS0tIG1sSTNWd0hVdlV4WDM5c3A1Zkpp
            ZEJnV0tORjFLeC91VEJYdW85Wk1xVVUKMSOiBE7lXaoEc1igB/OA6qVjD/Ws0gwR
            74wjMUeX9Bf+s29KVTLWeT0nc0exqwqMg5iQcsspK1zpnW2oY9mZ0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
    lastmodified: "2026-09-05T10:54:44Z"
    mac: ENC[AES256_GCM,data:W/Iqa350L+Rj+Kz/HknUOSHCshsWuXK67Uu4B76QQ6VpfJyxvIUL2WXW+C5yNCMcRN9uVwV1NH8FEHTcROVqnpMNAxcG+3BaUON5h+h8uHG7QTUgFiI48vVWt3fNI4dNj5T290zz6qwHQbRu7qbtuk+HSLMIV53iaRvlr8r9rcg=,iv:0nSwcqRoWFh0qRFR93UXlFdkpR+LVB1n0FmK6dv/r0M=,tag:8OjXuh+3IICfKMloVzepWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
