# SPDX-License-Identifier: 0BSD
# Copyright (c) 2026 Aryan Ameri

podman_host_packages:
  - podman
  - uidmap
  - passt
  - netavark
  - aardvark-dns
  - dbus-user-session
  - catatonit
  - containers-storage
  - systemd-container

podman_host_packages_absent:
  - fuse-overlayfs
  - slirp4netns

podman_host_registries: "{{ podman_user_registries }}"
podman_host_min_passt_version: "0.0~git20250503.587980c-2+deb13u1"
