# SPDX-License-Identifier: CPAL-1.0
# Copyright (c) 2026 Aryan Ameri

- name: Restart chrony
  ansible.builtin.systemd_service:
    name: chrony
    state: restarted

- name: Update grub
  ansible.builtin.command:
    cmd: update-grub
  changed_when: true

- name: Flag reboot required
  ansible.builtin.copy:
    content: "deerlab: a change needs a reboot to take effect\n"
    dest: /run/reboot-required
    owner: root
    group: root
    mode: "0644"

- name: Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Restart auditd  # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: service auditd restart
  changed_when: true

- name: Reload systemd for base_os
  ansible.builtin.systemd_service:
    daemon_reload: true
