# SPDX-License-Identifier: 0BSD
# Copyright (c) 2026 Aryan Ameri

all:
  children:
    podman_hosts:
      children:
        edge:
          hosts:
            edge1:
        services:
          hosts:
            svc1:
