deerlab_domain: ENC[AES256_GCM,data:RuTdDXQofwM=,iv:eIyVzwMdIPq6GgqoFG8rYsMRnZ1k+KVnUTGl2xJeYmQ=,tag:ybZnqA1sZAp+bvCOyYcxaw==,type:str]
deerlab_acme_email: ENC[AES256_GCM,data:kVamrGizh90h,iv:bEQuqhjTe8YurtlATpg+TNf7DZUB1AbDcph4VNrQv7g=,tag:tph2mCp2QOQOufmsuBHipA==,type:str]
deerlab_ntfy_url: ENC[AES256_GCM,data:q2hcFdupljGqhISavgv0x6pwZUqUGvaIBJqbQgTsGw==,iv:y0wXPtGSRK56T6i5pG4H+0G6GbjkBtRNIgQwvTd590U=,tag:E7ddue9tglqlS7+p1oA+eg==,type:str]
deerlab_ntfy_token: ENC[AES256_GCM,data:5ik9kKlBsLzw,iv:RGI+/qGuLg32xQ+PeA3wTANOSyptXCx73EamikfMzcw=,tag:XQlrvX0D73p+Ba4f30JMuQ==,type:str]
deerlab_root_password_hash: ENC[AES256_GCM,data:Y3xVQ+q3eegp,iv:REbfWC+VdKeAFaQGwEROSY3eGc655EEToppITuG3fwA=,tag:U8VGS5PYcrbFASoNzgy0SA==,type:str]
deerlab_deadman_urls:
    pull:
        edge1: ENC[AES256_GCM,data:1a993fKLNDjrZqlfBWAs2hppf4qSDCBsqZzzgks=,iv:ryLFgvydq0TYURapkon5qxyYHZ5tv6bcsnrvZkS+oig=,tag:XgV0u68qEX878rv01f9qpQ==,type:str]
        svc1: ENC[AES256_GCM,data:plnpF4qjzT+1/xtgWNsUk+gE759tbQm9jkzVd+o=,iv:TllFjWut4DKFN1ebKihFYn/+pjam5PsmYc7SljxAZjE=,tag:GMmfpCZzzqZaTQ9PMmFk6g==,type:str]
    backup:
        caddy: ENC[AES256_GCM,data:uIa6mGNArfm9UCq/oQjY7vjVlfdFYZFOyXwrTxM=,iv:8DcltzcZywssTUK23iK3LXyp1WzytKOaKizdwRPrkHo=,tag:1Kamzea3OYnyE7LEbhYmQA==,type:str]
        wallabag: ENC[AES256_GCM,data:pKqy7Enq1rTOOwdBRCwFcB6bAMa8XSiFtd17rMk=,iv:1d+NrE3mfXUkhbXBAMx1prlyn0Umko5rGGkT1JfqDaI=,tag:SsQdU5raEGTW2Ga2L/Kadw==,type:str]
base_wireguard_preshared_key: ENC[AES256_GCM,data:dpz7EVVUJmZB,iv:S2M/YN1lU/CjEvytzMrIvfPSBAXknJLvp4+DYGrj+F0=,tag:yOkcbVvGr0j0K/kuR0JWrA==,type:str]
backup_s3_bucket: ENC[AES256_GCM,data:2jroeip/x2Z4+we+cgn66Mm6t1n+RAzfmCeECmtB3rZL5JFdntsaMVhvlCQ=,iv:+MzLNI1YWscGc908HDD9pulPogQ9FwnSktqPZWO0Y90=,tag:tOXL296HTtQw5Gx4Ym7SXQ==,type:str]
backup_s3_endpoint: ENC[AES256_GCM,data:AnfHwGgt1TRqXpiMd9lp0ZOR/dZtF1xd6Q==,iv:HGs4s1B6kFVB0deQ/vxbvwwN4cDKlessUIpmuJTCVTU=,tag:W2xiyVv/hwIsD3T0cAZ/ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybzllVE4vRkxaNUdGSm5X
            dU1NOFBvWWVKL2hGQWg5NVJqUnZpSzBXRlVNClJBZklHK3JxRnRvTW9GUnVpaU00
            bEc5aHhZb0pTYlZlbXdRTUlvVlpGaTAKLS0tIDlWSUt5RGplS1B0dnArbjNXVlls
            SWYxemZQQXBPRXZrN1NSVXJxSHViREkKpUwSoS/9mftFIhSPz45VhX9FvuwttYL9
            DOlrr/DktvPTpc9V+BE4GvGt0OOH+StFFBgZU3u2JCiDyBuCCOb3Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
    lastmodified: "2026-09-05T10:54:40Z"
    mac: ENC[AES256_GCM,data:0i0asMMYGlf8L+iKJ2KuoFxddb4cTFOht5TdORZmxNwucAmjcjRhYJiPFFQvfVmDgbcaiS4DPdD8HvWxuK6XkB6lLqOWMjy2GEIYnT+i+/9ZE182t1gZk6HZSVNRPcMH6iAY7mtFeQt1luRe2IZFtjAW/oXYo0VYPyHvB7zNvYg=,iv:p9AzFiDtXIyTRAixW9vrjvzWQB9qNzCj5+9OaFgBsuY=,tag:U1d/y8g789rr2TieeWDWqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
