deerlab_domain: ENC[AES256_GCM,data:RuTdDXQofwM=,iv:eIyVzwMdIPq6GgqoFG8rYsMRnZ1k+KVnUTGl2xJeYmQ=,tag:ybZnqA1sZAp+bvCOyYcxaw==,type:str]
deerlab_acme_email: ENC[AES256_GCM,data:kVamrGizh90h,iv:bEQuqhjTe8YurtlATpg+TNf7DZUB1AbDcph4VNrQv7g=,tag:tph2mCp2QOQOufmsuBHipA==,type:str]
deerlab_root_password_hash: ENC[AES256_GCM,data:vr9sJsaKng4aODJLnl1zWSu4xFfoA1pLQuqmMamzsnXjghuKbkgkqg9C3rwIDWfcwBaucTRy3HxEj5opa/W3z2m/ZY/eqsYfCeNq/KMW48axzC+dDTSTeJg+tIKSnqwPJA3nPZT5uDt3cw==,iv:BnNyU4wQSjEkE49MwMWGkubuwaibU79z06Rckuylu08=,tag:Y4KyLttJvI8fma2Ey0UX3Q==,type:str]
deerlab_deadman_urls:
    pull:
        edge1: ENC[AES256_GCM,data:GqARlfRZkikTkTk6uJC6VtHOeQ8KSsPWRZcNgJV2wDpH7N3V,iv:13cg8Wo04iumqcXDMTmCu/yYrTnqkeGLwzXuj0dx8VA=,tag:tsk7c6nB9YT/7qyBEyLBew==,type:str]
        svc1: ENC[AES256_GCM,data:NRM7P8/4rmkLgwvaG3hgQbVMtlH9cTY2lHNwwU3KdBxQdLqX,iv:2hmzSbQgRZLzxC1xrGNStl84cY/FEPbIKjQDdT+OSRI=,tag:lvVp7yfTYZ4Hr07Lc72mWw==,type:str]
    backup:
        caddy: ENC[AES256_GCM,data:Nd6S4DqB5J70ZMrHmOh0GD2/4szgPr/qe+2Sy5NzjI4D9NfI,iv:FzFAx7UuhO8BmtmCs8w5Dw1TXxkKj2SjZKQI6zCLAR8=,tag:bjvvKFQhJcb9Oxb/vwzkuQ==,type:str]
        wallabag: ENC[AES256_GCM,data:p4ir9mZWMGR3jVWUlCnoQVtT20zWUV70+YpdHBzj5e77BNjs,iv:lhn9nJfwzwidUTJ+9yBMXL+96daDDg1ls/yqWbrzZYA=,tag:WsIlbKaEUomwKgLgNCuhtw==,type:str]
base_wireguard_preshared_key: ENC[AES256_GCM,data:Mzf7S6b6hMBgKJdAxMwfB9mIEi/VatMG4teJmT+r2RtyGE2vqrucxQT5rno=,iv:LbnjBWspO+GCCrEf8la7tDOiQ7/z9nQ/dZP2OeDm+ns=,tag:AUcYpNY5SYiGHByY11/p+g==,type:str]
backup_s3_bucket: ENC[AES256_GCM,data:2jroeip/x2Z4+we+cgn66Mm6t1n+RAzfmCeECmtB3rZL5JFdntsaMVhvlCQ=,iv:+MzLNI1YWscGc908HDD9pulPogQ9FwnSktqPZWO0Y90=,tag:tOXL296HTtQw5Gx4Ym7SXQ==,type:str]
backup_s3_endpoint: ENC[AES256_GCM,data:AnfHwGgt1TRqXpiMd9lp0ZOR/dZtF1xd6Q==,iv:HGs4s1B6kFVB0deQ/vxbvwwN4cDKlessUIpmuJTCVTU=,tag:W2xiyVv/hwIsD3T0cAZ/ag==,type:str]
deerlab_pushover_token: ENC[AES256_GCM,data:S1oru0ojHS5V,iv:quRjpKfCgIZ4yidGUrleopCXVYqNQ60zu8ZV7M9ZBwA=,tag:mR/2fvk4Vlxh+gOQN9A6og==,type:str]
deerlab_pushover_user: ENC[AES256_GCM,data:3v1jzUK7qaYi,iv:dj/RtFw03c5Iv4CnS9sQ1GoRFcdtIm1YDsXgNV3fDPI=,tag:86GPkXZjHQRG4FaYIE1kkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybzllVE4vRkxaNUdGSm5X
            dU1NOFBvWWVKL2hGQWg5NVJqUnZpSzBXRlVNClJBZklHK3JxRnRvTW9GUnVpaU00
            bEc5aHhZb0pTYlZlbXdRTUlvVlpGaTAKLS0tIDlWSUt5RGplS1B0dnArbjNXVlls
            SWYxemZQQXBPRXZrN1NSVXJxSHViREkKpUwSoS/9mftFIhSPz45VhX9FvuwttYL9
            DOlrr/DktvPTpc9V+BE4GvGt0OOH+StFFBgZU3u2JCiDyBuCCOb3Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
    lastmodified: "2026-09-05T14:21:12Z"
    mac: ENC[AES256_GCM,data:ZJTOE3TLkxNF6vjUoqWAHaRzJn24HoEtMGqL9wC1lDBqjxgO1xA171oj4gqw0qfkpHf6VqkOoh6wZXwE21Z2n8a8LQhPG3CNA5kKNcD7dq0zRFl6TRCact2peWKs5hMVLKuhcm9yfUJXSrOVzGz9OxbDKKZMYvg11GPjHVMs+1Q=,iv:02o+BfNnvfHHvqDQjOmHCI2vld27hUcXAPgOThmItz8=,tag:ugfYs+R8pwe+dCnl9SedzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
