deerlab_domain: ENC[AES256_GCM,data:RuTdDXQofwM=,iv:eIyVzwMdIPq6GgqoFG8rYsMRnZ1k+KVnUTGl2xJeYmQ=,tag:ybZnqA1sZAp+bvCOyYcxaw==,type:str]
deerlab_acme_email: ENC[AES256_GCM,data:ZfAUM9NKooOFe/40g4sqZtL0uihWJM3cO3g97g==,iv:QlrdBLO2SdDdfiHft+V1PbZZBL+dzmaiG3cd578Fz8g=,tag:OaK1D4GOQFYXbiKeLm5oKw==,type:str]
deerlab_root_password_hash: ENC[AES256_GCM,data:s7xeXqxn+SMMXge1Vx4MTyfNWxDmJXLCZ0kjmUXzDPbITL5DZXGvAyFbdt/qULPGLVbAOWyqCe3b9D6uEkuwPOuV4FjPvxByoUbaTk1yHr86LYk5t5S3Dbe522myMmyALfNchjSACwd2/g==,iv:uHvizS2XTKCwaN6rhcV3oNl2bo82BkTMZxcYSkcRgHU=,tag:mUKfvCHfibu+3GFlon5lZQ==,type:str]
deerlab_deadman_urls:
    pull:
        edge1: ENC[AES256_GCM,data:X4e3Lw6BSAZ/+rNIXny78gMR5BtFwdeMjjJJzLlEYrlaimV2NV3UiLEY6ZsOnexG1Bgbx3/KWoj05BjZcSAQZNqzlVjvFF4NnFzAJc0FmHcn0lxCQCEzJw==,iv:jv55IiUmvGVyY7BFIohdSkZOVpYYPiyAEXYfguj7hXw=,tag:VmCQiaCHWHE1tm7DNOGh+w==,type:str]
        svc1: ENC[AES256_GCM,data:OE9rt5k93AfAq3WxDQcuKNCTfIWz5DiPVDyKSKVSUhbMhR/1bGy19cuoCTPPXKedQ7G5dlIuvnK1QKpA9l3BnqWOCrvXezVat0Xhsqy+eesl4oL/xcq1hw==,iv:ynmWBYz1Ku2J21uMu9SNU7h6vNQox8RuqAyjgmjl9FM=,tag:5tCPHUAgDOiVarEmpI8dpw==,type:str]
    backup:
        caddy: ENC[AES256_GCM,data:+V3Og5idK4wUD+dwMGJZxBjyELpHQ+KKSKD58uttduyWVyDM/dWiNfyva11xeo9KxkkMwQyEyT85m/BlVHxA944SPS3LOZPhkdt7Gz04zKIndc5gKssq2A==,iv:exB+fCu9/KeDcB52duZ8YaL7glWgh8Ur4F7GCZkhE7c=,tag:XqFRRmiTRYXlk/XZJ2R+sA==,type:str]
        wallabag: ENC[AES256_GCM,data:uQGpkJnaiVA1Cbk721TNK1CtcwCqi4tI3Ny8OU3H+0Xzdrh9p/SUuAq22TMIli+pansngHn0/jFn/H3f/ONRVRze2V4OUYJaUMtW9UQ8shrEIYyg8kaV9Q==,iv:ZPge8UwFaak6vGgG+KfA1Q7NYPHdzfn67xo55VJHXxk=,tag:Hoy7a1lfncNJ7RVxWLzgQQ==,type:str]
        linkding: ENC[AES256_GCM,data:3d/pI+MW7kcFmvyjzTPYwjPflWtKmZXqs2cs2RdrLHXp1tvKW1v7Q5poad+JlACjKS7UR2MI8KiuIzwIJVHG5Jte6Lb5Zi3tNPR8+K7hypuBR0bQzbGk2A==,iv:AnbETuGYAjEK1lDannUh685u9ZWtjhEYP0IzT2qxl4I=,tag:DSpkc7EQ3hWNvvVhdFGKPw==,type:str]
        baikal: ENC[AES256_GCM,data:tPBByvFUzXlD9lmypUMsNfJwxnjA9M5ygYFJRpUHiJAUk1+yb+XaTKlsluOyYJAI+oVlDN5ryvNvCnYHEeBcsbbsChufWQXsAhDPOSiwvTg6JTsZ7FsMbQ==,iv:dWW2pLWqCvJrpdKidtGrZMjbL3y4h4oIobRNsYtJupU=,tag:9ZeyFbxSQYDa1srDEKOV/g==,type:str]
base_wireguard_preshared_key: ENC[AES256_GCM,data:oAMPROqoAH14rImX1d4lJC2liR4KWZ/Qf6TbFe1/rN57mB05k2+kb813NMI=,iv:vXFHmY95wch5Xfe61HspxM5I+kRt1zo1hX38VAXnSRE=,tag:7OmEYSVAMaeJcq6Ktpr96Q==,type:str]
backup_s3_bucket: ENC[AES256_GCM,data:aiWNyHvs3R50NiY26BQ/7zyLsiRdc2z78rd/M7laOvL3KgBWjTy+nEwyvgfAOv1larzdp0DUcKE=,iv:wne3v02DiMDaY9+uAfALLXSjqm+BphQgx8GMbKlE6vU=,tag:RvmUzBUF8B5GiPJgu3NcsA==,type:str]
deerlab_pushover_token: ENC[AES256_GCM,data:6V0r4mIw9cCVEXs5S230uPg0iAMm7YmPYf6t8QUC,iv:YAqI3sv8bQNN6SE8wmEjuZZyssDcTqFiVOduQtZTSDE=,tag:5ePWFKm9eBtY6TQO7E86EA==,type:str]
deerlab_pushover_user: ENC[AES256_GCM,data:rCmGIgtjKSVCXDrp2sTw+a5oTDjRYP9iwcA1XPKS,iv:/qVKFl/mJnTh23I+bmFEokBjnju+rvXt2s5Y7QYz6RI=,tag:8MJRLiw/O9N15+rtF9nsmA==,type:str]
deerlab_admin_user: ENC[AES256_GCM,data:ZCLGVhpMaQ==,iv:tgItEKCFVh3y72IS+7gYoPegIlnEbMnYb5IxEsaV1wA=,tag:lSUpeGqnnVVGTi/ESgSYUQ==,type:str]
deerlab_wg_port: ENC[AES256_GCM,data:Cunt5Hc=,iv:80vZ5AwwWMFSwz3e5Mz5UQ5Rpgc8IMLSp7KkmzU6TXo=,tag:4oiOnijnuAkvOcgUQtyqXg==,type:int]
deerlab_wg_ipv4_prefix: ENC[AES256_GCM,data:QfxYizTWwNr6JbAa,iv:bGubfN1acZTUh/XdwKFIc0fDsd1XJ8xeTQcnGKXfi6Q=,tag:WAJjM6wsc2P3okG4IHjpsg==,type:str]
deerlab_wg_ipv6_prefix: ENC[AES256_GCM,data:D3Uj8wZGv9ct8JyAJsHkIaI3qQ==,iv:bkCaalwCQR+KTtVfnAayQzTWxz3bLL7Ig47YBqDphew=,tag:OIVB/3gc26faYTcSMlC1YQ==,type:str]
deerlab_admin_ssh_keys:
    - ENC[AES256_GCM,data:1jIbQiF4HjDyFhnsKCcONE9OP+BcfCXQg6v3r+ElqIw+mvpkfa8VHkugBiyHrVzKDejtH/73aRTthHCnMqgKrTvFp4sLNyENSGPJpfhx1Su3HMavN++dbg==,iv:hZbkeNvyl+epsJJEWtioRHbrodOayaPZMHgLTqL7B7Q=,tag:JVpLwTDOqjMwuK8+BPn6Zw==,type:str]
deerlab_allowed_signers:
    - ENC[AES256_GCM,data:ALwpZQlNS51ZXzDdpN/9FabUoIC5vHGWeWrqRQ/AL87CYDik5W0Ob7/Jd2YxtHIxT6LcFbimC9qkGXzCKnl07YjXNtwYG5rUgOdqCEBnOa2d5Gq8TxrAD06P6U6MA7rhhQTz9RawYcpjIg==,iv:zh/C85V+dgzcIaM/ZQJrEJeeu0sE1JuybRCFvVRcEzk=,tag:8y1Uc3F83FsxVNeefR4HwQ==,type:str]
    - ENC[AES256_GCM,data:EGDQLm5XkeB59G8VisdRxxNWrPVxMwh8l3Cq7FtI3QyDeWncC5RsHQtCV0+Xk2gZGufH/JkTg5KI1XaIzUhVtnL0nZf/y0QNW6LPC0ybSvDhnLoMcNcvD+eVtnf6FTgCOg+N7Z3QogdJOw==,iv:3E05qGD3NeqSTie5qkY4/u2PV9visZxAP6xCeYf8Xbk=,tag:oo0bRLodlZgQMvI8g+ugbg==,type:str]
    - ENC[AES256_GCM,data:ZR6CDlCootFWtX2VYMsFUirLtlH5oLzT4mXDZQnhhjRBuS8Kbdj/XtrH1nI+w3ww6RpnidzKqT8vB6juw8qfaiS1plWMAXz2ffpr4+O+Wnxl9695VGbkV8q8U72gG6ujfc8vZ91qM8vuhg==,iv:9H3RHxSPXWuGYaHQKW3vHsETGP8M89CMHiViT0GINx0=,tag:7bAggBYlZt0i1j74uRMoiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeGN6ZHErWEJEWjdaSGZp
            WTF6MmoweWY0a2FOakJVMENKeVV2Wm9vTWwwCm1OTkhEOFZ5QmVtUHBJQ2xCZFVp
            UmJic2pOcmJ4Vy9EZGZFTnN3aGd3aFEKLS0tIDBFWERwRmYzUkhtcTh2ZmROY2g4
            UVFDRjF2V2txV08xaDZSSi9QOGUrbVUKbSpcmyTyocFPoJY8eOIftTuNoRW+cfoS
            Xj4lya5ONU9GMktJ2R8k8wlLwSwEMulQWLnj6QNwSdT0yE0eP9xvHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQkJ3V2lETXlvSzVxWTQx
            cUN5eTcxWTE5WUN6MFhvWXhUTitmRmZ1V1hvCmVQTHlNNUxkeUIxQ3E4VktQaXlo
            OW9GandFQytqQ3N1VTJCWVVvbWIwMFEKLS0tIENpOWVwa0FaTTdJbzdoVThFTHlx
            WmpIY1hnZEVYUnpORU1qSmhsMHlFMjQK1MG6w35aoYFc71KQ86oSnQHGGPBIwMdZ
            PyeB16HRuFdTflJNDC46eXMDbFYdbqDqvgOuF0PEE+v/Bo+PXqyp3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxhkt6syw8mmfzzzgf9dtjkvt5j7au36nnsmv4vvuejdwmpv9ftssv9vkq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYTJtYnJNT0U0TlM3TWR1
            b2UyL1lEem83UXUvbHl3Sld6VnIrcjJFOVI0CnhTTDZxZGMyMDZSbGZDTzRSYk5p
            dWRGK0pPYkQwTWFkekg0d0g1RDBaaGsKLS0tIGg4QkZvWG1rOHZZK1QzOTUyMS9G
            SmJkL2g4RU1tNmE3aUlaN1U1TG9LK28K2e2qDdi20U2wG3f4dZqWyTk5lfTskj5u
            xMsbZXjcM8F/svmyiNXlUoF9fNGRxZNqdoU/L3Bn95vT+DvEfts4yA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3ze7nymx9tk78r78mukpxjjuhhaxh2wqz2tpem9ymcgngr94f5qg434hl
    lastmodified: "2026-09-11T07:23:39Z"
    mac: ENC[AES256_GCM,data:xNdoH9h8q2TAYVUbyBhq3gOcMpXtAXeSWBgxE5Ecx7vUCZqQfwix9C4E3PJea75zpGDdHZiwJTpBkbFo2jml7ETJgVKq9MmPXYbdA2ErAtazbqjEuRzaSm6SxzsVNJDmycrBosPJImab0ff/pS5kBLjx/fpczdmj4U02xHnYxe8=,iv:z8COK/MBhDU3/w7ACn1++Man4uWLK3GtpMnlTKe0rrg=,tag:kc2eUkcVn3KkxBsgFvtT+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
