wallabag_symfony_secret: ENC[AES256_GCM,data:JgXqJQ8+E2T2KpTtMjVVN7LuIOY6dezgW2XHKkRTht8toR+rArpcWySnlHtIw0qBcWD1ubIRf9gOjtAv/oAMWg==,iv:u1irt8WP/5v3xKem7uR8xHog0xD3GCbU+kYNFWjxwbU=,tag:I1GpOj3oWr12+8ucA2GEMA==,type:str]
backup_wallabag_restic_password: ENC[AES256_GCM,data:7I/FD6ctmtLRRvQEu2XaZOdUZaih8nNc+7c5+B6OhOsZ4oWIGkSG5uVs1aCXhrrze+1HJQ1hnfLn4Dhz1XfLpg==,iv:gEuCjJhHFfdB/IXbaz5ahOrR9pQ2x81wBvkNOEQyNE8=,tag:HFcM8f57DSwSlsWewI4iug==,type:str]
backup_wallabag_s3_access_key: ENC[AES256_GCM,data:M3CdTdaN0a2KyYPbHLmPllk7Ew/ljGx0IQ==,iv:E20uMychv58xgFUKqnBngLyABDqlLlhbBJshjfXUWb0=,tag:ElFjMlg9RgnDMzLv7j28hg==,type:str]
backup_wallabag_s3_secret_key: ENC[AES256_GCM,data:88Ev52IduWA5/5RcYeZo1mCbXVjrcR3eb8Zd+ESKgg==,iv:BAC5BTQeRt/O+a7n9lg+cXn8YqeX6xRyf822ilDCLn8=,tag:tCF40zmRGYM5y0pDcH7ecw==,type:str]
linkding_superuser_name: ENC[AES256_GCM,data:bRCHNFU=,iv:T4IpyUuC0Vbs0qHQjJJeyooQONztnZ4Ocfr9uTP95cE=,tag:UpbG/HdE2H7tnmAd2XZHnA==,type:str]
linkding_superuser_password: ENC[AES256_GCM,data:QCg78880o3maaNrtsW6C1hQB0vUpJlDGdL94OjdZy7dsTs6jZf2T6QgJwae/iIha,iv:5R60ruHjakkjRFZI/UT1G8vjWsZjrH5x1Sqo1vbV2TE=,tag:rRzgzMoqOYfcmH/GQIhH3w==,type:str]
backup_linkding_restic_password: ENC[AES256_GCM,data:WhQOzFu0Aq8KK5rIhoBdvg1TH9dhrQ7oNc1bu9FVQL5we8MzPvy0ZrxJqwHbQr0txTUVzg/AkA09HCjq,iv:8pZZb6fFU2Jg4h0VmDQP+u2XjY+07cJQv/vyWoWBW3w=,tag:928R/Fqucao7cpMo8TSWpg==,type:str]
backup_linkding_s3_access_key: ENC[AES256_GCM,data:TTJwTys5y20QK6oa62QDF+D/PuyjIPdUaw==,iv:ySqekIUJq2rBc841IrV4AqHySmf9JwOFzKGhU3V84ck=,tag:pyuxSJKz1bTUvoChpCIVBA==,type:str]
backup_linkding_s3_secret_key: ENC[AES256_GCM,data:IYUGdRcD3NJGsR8nyF5/pik2xtkgnA/kMxaOj6nwyA==,iv:E8gLO59a7STw4OTBGgLeWWWJKyW+d0m/7/lKKRPJ7cw=,tag:8PTuP8t574oxU8yEul+s+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdG1iQVUxYkpYclhhOU1K
            T2NxaWxXTi9vT3I3UExXK2tWTzRNRUVUSkdrCkJ6NnEyQlpObnRvRzNUTWNoSnZT
            VWp4eWZlNzRldGtQNGZSVUxvRGtaNUEKLS0tIHZTbjFXQXBySUJIeU5udUlZRnlu
            L3pWRTRMbnVoZnVQZFhtRlc1bkZXWXcKf+RpF+tr6vQLoUMGT/zfE0nOJWjY/zWc
            b6TC4vKL5JtKWVvNdflsBsxbgNZFx+DbbRtOgL+izVN/dbzPKJeIlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc3FERjBKQXZEZVBDWGJI
            VHIwRGZnMHR0dkhmUFI4bG5kT2xidXo1aEF3CmwvVTB6NE4xZWtkemo0RitCdEdI
            aU9JUjYzakMvT0FxQjZkd2QyQWVFU3MKLS0tIHUvVE1qSGpxeWUrZUJqUCtjck5W
            Ulh1L2dxdFhDcUM3MFcwRlNNQ3UvQ00Kmnr7QGBNw8ta6cgDek8RSntD1cd8CIMm
            v/I8cUCpeTzIj3Oa14keNhv8KXx5h0rblxAHAeE/nbeMs3uahyeomQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxhkt6syw8mmfzzzgf9dtjkvt5j7au36nnsmv4vvuejdwmpv9ftssv9vkq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNkc4VEhaN1JiV0NabUhi
            eUd5dWlFRFVsdW44RHlodTBidkRjNldPMXlZClhaQUFpUzJsbmNVb1hlOEFGUFZ6
            UzlHa1g3dWRTTGw5QjdJai9DQ3hKaUEKLS0tIGx5Wm03Z1BidnV4enpZREp2S0xE
            WUkvVXZCeC8rYS8xQ2xTTFVMK0txSDQKggejZToZnhtxNZ3ECsThOcgPUrFeN27y
            7124Bc8CTxIDbimqtnMB97iN36WFt/mZz80OBfy9Ut+sAgbwnInG3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3ze7nymx9tk78r78mukpxjjuhhaxh2wqz2tpem9ymcgngr94f5qg434hl
    lastmodified: "2026-09-08T11:59:02Z"
    mac: ENC[AES256_GCM,data:Tp/s1TPMlFrZpODeFuLVnezw1qpkPWXMgR0bXM4GyC2WrdwYUeMind3CNNzCguUtMAJP2oN30/fKjyG6MhRrbaioeb9NRWMLUMGH423dKOOwMQRvN7a3wrQ1PO0M5uDSssvmem2wvpabw74z1jTDS95fCEhz2BALuhv1dSr6XjI=,iv:ZpC3XXfPHmQvNt2X3xbWqzL/kSzlsMdpuqoMfzhOJ+0=,tag:/mGXp7xNljEAjEau12NSaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
