wallabag_symfony_secret: ENC[AES256_GCM,data:8IckIh9oiYwT,iv:De3C+Ytch4YVAq8hZwgYhbfP7qgcd49nPd2o+nfpIhM=,tag:oL42qvYzPsPjseD9RwZKhQ==,type:str]
backup_wallabag_restic_password: ENC[AES256_GCM,data:tz287tWmUpoA,iv:QTvMn+v1JJrvcTYPTA1ztXuhE0/zYPIDV+myb0XhLR8=,tag:2xTM/PfxoF+fZ20DVkaKrQ==,type:str]
backup_wallabag_s3_access_key: ENC[AES256_GCM,data:et4sy7tVRM0W,iv:7Y+MX0jjaODYfdR34IesEdiIFAJrkXMsWZiXJovhZVo=,tag:Vv/S5mLo/XkQrAMXhUtcUQ==,type:str]
backup_wallabag_s3_secret_key: ENC[AES256_GCM,data:4osAgO+F3Roa,iv:HWcmKLlbODDQM7WdLpg+hjo9YbET9gRLJFt9+bslYGA=,tag:J1Orv0jvaVu+v06E5Rg0sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWXIwaEdKODBvS2svalh1
            aUl4M2U3NGpHd0toWXJXNTVhQkdFbk52d200CndXWGc1M0NhT3pEUmhKTGQ4K01X
            SldtUXZPa0hDMjhsOENhOW00bWJxUUkKLS0tIHdHUWNOUllISUtqWlVBb0tpN1Yw
            dEhhYzRmTE45VnNaWmZicWF5N3FFWVkKhNhWIZhP2nfhiQNyLMP9XgCWih5MX0s1
            /aCn5kILO8qg8GyHc3Lqx0PsUucoj+9gXa412Hdi3iA53CrBF0iXkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWnJseWprMG9IOUVtZ0pI
            Y3pWa0hYU0tVdW9reWw2Y2Z6SitBTG5ONWpnClBpZTRjR1hUNVVISGlzMHNZVXc5
            K01lUndHUlQ2S2o3aDNGQWFySlJYZW8KLS0tIEN6c09VV3UwR2R6WVlLQTVOK0FH
            b2tmeTQ2T001UGlDcmJSanIrYkk0N28K8hn/LdN/QCmAPykSAEUNc59vfrncReGK
            SmCzxQPyXk8KFz7QIeHcevfkwhoYDQ8uYNgksAIg71+TyLVj5qpB2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxhkt6syw8mmfzzzgf9dtjkvt5j7au36nnsmv4vvuejdwmpv9ftssv9vkq
    lastmodified: "2026-09-05T10:54:44Z"
    mac: ENC[AES256_GCM,data:rOZpRjhc7DB2/Dubf74NADpLiTH0Gu58HpDBOo6+KoFQr8hayji+l9g7f8wj4eJ72De6j/kpfKXA2x68rqMOJYRwHex2k1fnoF1BDFLoCPW35J1RUMAicXtt3mQGmh0Cvnrt6amFrJjH5nG8oZDyS6SjmQy1m3wNtXlmxeXSlN8=,iv:64r+XIm4tfohHqa1TFYnNTL0Yg7BQXQAac+ufl6bu3Q=,tag:L2cmJF5kKvKt6BQwTbjq4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
