base_wireguard_private_key: ENC[AES256_GCM,data:b5MvEGq7qNrZYIw6gZ2nu/S56GqraNUEdCAvvDgWZIdqJsBRkwpyBPnSmCE=,iv:99+ZcD2KoWsk8JaueOgroharKkMkQp3BcXcTZ47OqrI=,tag:/3MeX/iRrztbHFxcWJEy1Q==,type:str]
ansible_host: ENC[AES256_GCM,data:/5fa+zglWPrXS7xJsw==,iv:xA1NAQx5O6mG7k30WrlBOedn0opiRHikyAMYJJL0W1U=,tag:lnzZBZfT8uSmFxExEwezkA==,type:str]
base_wireguard_ipv4: ENC[AES256_GCM,data:LopiCxaRLTNQ,iv:QJyUEkg1pgd5HzI5dtLSopAY85JAaJKgTJjG8s0YsRI=,tag:aDQxbvhB4WD7prCjxOWglQ==,type:str]
base_wireguard_ipv6: ENC[AES256_GCM,data:xx8mC8BTdSNFSqPbSxkTSkI=,iv:P1Q1NV12uGYYN2OPp+L6ge2yV5DYcCSN+MQfhTVhgvM=,tag:TKnWOkAzvqXTtbztC5uQUQ==,type:str]
base_wireguard_public_endpoint: ENC[AES256_GCM,data:EYuPzMy5rNr7c104RyDB9bHRXw==,iv:5+ThbDCGwPvhvj1WSSnMFrrhhBJcdsmdBSFdgEaSb+U=,tag:ZTDY2ZEqy++NHHTD+4sUaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNmttMzFKUXFWOUtkQ2NG
            K3ZRUEl3aVQ5alhHTEtETmFjdlRIMEFsRnhrCi91MVN6bWtUN05xZDZpdlE5NDJE
            ZG03MXZBNHpPZ0lYeVNPa2N0akcydW8KLS0tIDdMbnlFenVNUjIwcm5UNU1SZ1h3
            MC9IMmJCK25kcFl0bFEzRVFQSlNTUkUKeTwp9+gG2Tf63/eMCIUCTO83vz6Ar8sL
            jYHXyC4WnPda1ckCVLiziGXUsOmlIE9bTAtDgKGXX84QHc5QuYgWLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
    lastmodified: "2026-09-06T10:38:26Z"
    mac: ENC[AES256_GCM,data:znjJrDskP6VnTVzhIlF4dilPP+Q48a9iqSmXq5Uk4mG1xtsBb5Kgrm4I3+BNaKygY41SUtfccsGGbzGQSG1QjfmaoIVrHIX2DNFEatKpEXTISySyBgAdbpfzPodLwNv51IguTIi0BdP60U/ASZE/D4S5ctuwfGuUpoZZVh/0vkg=,iv:k3F99noqABFJPEufapKQDeJb8+26Qj0B7U9nWsnivLs=,tag:3ZO7q3x0nlsowruaxBCBTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
