base_wireguard_private_key: ENC[AES256_GCM,data:b5MvEGq7qNrZYIw6gZ2nu/S56GqraNUEdCAvvDgWZIdqJsBRkwpyBPnSmCE=,iv:99+ZcD2KoWsk8JaueOgroharKkMkQp3BcXcTZ47OqrI=,tag:/3MeX/iRrztbHFxcWJEy1Q==,type:str]
ansible_host: ENC[AES256_GCM,data:/5fa+zglWPrXS7xJsw==,iv:xA1NAQx5O6mG7k30WrlBOedn0opiRHikyAMYJJL0W1U=,tag:lnzZBZfT8uSmFxExEwezkA==,type:str]
base_wireguard_ipv4: ENC[AES256_GCM,data:LopiCxaRLTNQ,iv:QJyUEkg1pgd5HzI5dtLSopAY85JAaJKgTJjG8s0YsRI=,tag:aDQxbvhB4WD7prCjxOWglQ==,type:str]
base_wireguard_ipv6: ENC[AES256_GCM,data:xx8mC8BTdSNFSqPbSxkTSkI=,iv:P1Q1NV12uGYYN2OPp+L6ge2yV5DYcCSN+MQfhTVhgvM=,tag:TKnWOkAzvqXTtbztC5uQUQ==,type:str]
base_wireguard_public_endpoint: ENC[AES256_GCM,data:EYuPzMy5rNr7c104RyDB9bHRXw==,iv:5+ThbDCGwPvhvj1WSSnMFrrhhBJcdsmdBSFdgEaSb+U=,tag:ZTDY2ZEqy++NHHTD+4sUaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNU5xR29ZRVVmS0I5aHBi
            c2JHOGtxWkxqUnY4RVlHVFh5eWtOd0xjUFMwClpnMkx5M3pFdXdNUGtQa21pcFlF
            MmpYdjlXR3BLVUZva2NFV1ppTWtaMkEKLS0tIC9leGFiQXFrd3ZldnJHQW91cWRp
            VWNLMHZoa0Fib3lMN2cwNU5sUFdnNWMKmQFbu5N7EjJwY9HHtbbYnlOEUYOTvKvC
            KXCmpyX58421/UP7CnMdO241pz+/+CgqRX27qcU1/EtUMPST7nV+6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSWtoVHdMZFZzbjBReStw
            ZTJrV1g2WFZWQWR6Qm1QeDZ6T0dJckxxdFU4CmxoNWNkUmxQeWhkcXlJVk9VOThZ
            STVyVHlTVEQ0SFpiZzM2WXZRR3lERVUKLS0tIDBCZHhrRkNSR1BqOW8xNVVZUFMv
            UzlqclJXaUtnNnNBWEIyYjhOSU9CMmsKcEfqovI0T2k4Hs4CpN1iqL9azs+ZCRHK
            hpDaABEUxUkE2KFgyYumD4Zc5Bd85JiMvjyDYQ2DVLnKmqsTYqHpsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxhkt6syw8mmfzzzgf9dtjkvt5j7au36nnsmv4vvuejdwmpv9ftssv9vkq
    lastmodified: "2026-09-06T10:38:26Z"
    mac: ENC[AES256_GCM,data:znjJrDskP6VnTVzhIlF4dilPP+Q48a9iqSmXq5Uk4mG1xtsBb5Kgrm4I3+BNaKygY41SUtfccsGGbzGQSG1QjfmaoIVrHIX2DNFEatKpEXTISySyBgAdbpfzPodLwNv51IguTIi0BdP60U/ASZE/D4S5ctuwfGuUpoZZVh/0vkg=,iv:k3F99noqABFJPEufapKQDeJb8+26Qj0B7U9nWsnivLs=,tag:3ZO7q3x0nlsowruaxBCBTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
