base_wireguard_private_key: ENC[AES256_GCM,data:4LjM5ky6+coJ,iv:h/g+KbxU1yyQGrik+KTodySyrDSYnh7HbVgsWJel+uQ=,tag:4Irg0tS9Y5Nir/uKgQt4mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNmttMzFKUXFWOUtkQ2NG
            K3ZRUEl3aVQ5alhHTEtETmFjdlRIMEFsRnhrCi91MVN6bWtUN05xZDZpdlE5NDJE
            ZG03MXZBNHpPZ0lYeVNPa2N0akcydW8KLS0tIDdMbnlFenVNUjIwcm5UNU1SZ1h3
            MC9IMmJCK25kcFl0bFEzRVFQSlNTUkUKeTwp9+gG2Tf63/eMCIUCTO83vz6Ar8sL
            jYHXyC4WnPda1ckCVLiziGXUsOmlIE9bTAtDgKGXX84QHc5QuYgWLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
    lastmodified: "2026-09-05T10:54:44Z"
    mac: ENC[AES256_GCM,data:RSBTkeNfPNNSSzXABUYdCowCIHquv5yPKVPv1ezTprioLq3W/e6+n9fALpS+a+HZA8AqXyh30YTKGLJ8BddzTbuhpimc7VPvVK+RL8VnOcplCSFwR1Lr7jFQZkWvP/4A/lE1q+OKFIX2DQjTFHyMDyxof9eI3+ialqWMRDRufrg=,iv:+eK+FbcVbrl4bMcPoRMCR6osbtIcn3Lzf9zoIm+kIsw=,tag:h3PLj5+sFQ7XdEX/vnsDUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
