backup_caddy_restic_password: ENC[AES256_GCM,data:MvWsuzZljExVP+ogPxo/Id8PM4e359vZPdYNRuy7I1QRFYg1xRSapanqA4udwhlWSCLo2xnZqM8uRKNStPlw/Q==,iv:hv3n3/TTA5DkqslkY3KPRLEG9U6XDi+j+LcKohQwCHg=,tag:Y7K/XZNYdGo3JBtwoA8moQ==,type:str]
backup_caddy_s3_access_key: ENC[AES256_GCM,data:mLdgjUB4xAR63w/FZC3WzrkFvlJeoojEGg==,iv:MCj7gUBLf4i80QsCE00yba0GDIkl2TAan+RWtnA5rzk=,tag:YxvK1fCY0CPuRCbc1KSMLQ==,type:str]
backup_caddy_s3_secret_key: ENC[AES256_GCM,data:TCwX9vykEJlloixbefYBYkjCaQsHsrDqEeT4Jyw/8w==,iv:YWLcq53cGh0p/u5TRhnhovUjCqU7Gxz3R/ebgjvaY1I=,tag:N8pzBYG6dHXOg+PnEclEWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS0l4Y3pJS25nRWh3ajV3
            L1hZSWtmdkNsRlQ3eTlVZmp3dW82bHliMkdrCmUrTndXWjBUanE5RkZibG5VNis5
            SXQ2RlhvSHZZWFYvMEhpTmFxRXFVUXMKLS0tIEFRcFNNSTZIMUxBUksyamxCVzd0
            bGh0cHVYQmdtMjRJYzZna0RyZGZFdkEKegAK1iO1nch0tySps7J4r7ueFd7e2HBm
            Epzwo5mBlII8NA2EzIK06QHN4wmjPimltDBOTZX37hdlAmsbpxEjFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUTNIK2JpT0ZPSUF1aWM2
            R2Eza3U4WFB4eW4wUzR3WGhVcTVnalBFeFNzCkdMcDNwWTRqZUZLSEtaVjVTQnEr
            aGFuWGp1RDV3QmozMFlZWHlWYVZhemcKLS0tIFlZVGJnektNaVliUUpmZDhtS1Zp
            M04rQnF2Y05nMHVUVEovWXAxWWFKMFEKfrdGDG2Gfy3W40ELFTljYH4edPLjvoJC
            O+INFPf4j06NKdUowl90wvgcbsTCeS/vu68a/qCGZFs34oA86996Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxhkt6syw8mmfzzzgf9dtjkvt5j7au36nnsmv4vvuejdwmpv9ftssv9vkq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSUlqTDh1YkRzZEF0b1Bv
            Wmlua1pQWkdMR2ZtRHJEVXhLQmFxQnZ1SEVnCkNYM2ovbEowZ1FiSWl2TXB2a1Jq
            OHdDK25yd0JKUS9PTkw3bU1TWFFMVU0KLS0tIExxRDgxOTZRb3RyNG5vZzRjUWlG
            bnR1UkpSeFlxWWFkcGJHSGtIcDk4bncKe+Z7kouDZntfqv/Gwl6jDzyNMwTrcPiV
            VV7SooPi5CnKfvr1o0AHaWlITYLSUUj6HNGeoqjGNRyXSM2MdL0nCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3ze7nymx9tk78r78mukpxjjuhhaxh2wqz2tpem9ymcgngr94f5qg434hl
    lastmodified: "2026-09-06T14:10:27Z"
    mac: ENC[AES256_GCM,data:VRMugV8Owsqrfq1lo+9GVEQXjuJM+9Nn1GUukUMI7B/7XYc3kaJ4XRj61fd51gZ2g1B1p24mcV0g6b5ll+crmcFtxv51vEUpBbdY/Y7Ca4LoeyJfI6BkAB7AKNxgzQ+d9UgHS/iT1cyh8uZwRmem7tiY3pi3Il8drAmbSU34m90=,iv:1Ftf2AcSM9W4zst3TlwKpCHb304UchC+ygQamOWmzUU=,tag:cLkxwK7TOe+o0vD34qpuHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
