backup_caddy_restic_password: ENC[AES256_GCM,data:MvWsuzZljExVP+ogPxo/Id8PM4e359vZPdYNRuy7I1QRFYg1xRSapanqA4udwhlWSCLo2xnZqM8uRKNStPlw/Q==,iv:hv3n3/TTA5DkqslkY3KPRLEG9U6XDi+j+LcKohQwCHg=,tag:Y7K/XZNYdGo3JBtwoA8moQ==,type:str]
backup_caddy_s3_access_key: ENC[AES256_GCM,data:mLdgjUB4xAR63w/FZC3WzrkFvlJeoojEGg==,iv:MCj7gUBLf4i80QsCE00yba0GDIkl2TAan+RWtnA5rzk=,tag:YxvK1fCY0CPuRCbc1KSMLQ==,type:str]
backup_caddy_s3_secret_key: ENC[AES256_GCM,data:TCwX9vykEJlloixbefYBYkjCaQsHsrDqEeT4Jyw/8w==,iv:YWLcq53cGh0p/u5TRhnhovUjCqU7Gxz3R/ebgjvaY1I=,tag:N8pzBYG6dHXOg+PnEclEWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRU1FbEtjenlhQjlicG9o
            U2VndTdHTFdqN1NrY3QyOXJLUDBlQ1RLaFd3CmJBSW9KMllBWFQ3R0hZR0x6Mlkr
            Q3ljN004aGlRQ3kwRWhLZEdWcE1Rd3MKLS0tIFZUVnYzMTdsV0lqQlZHL1o4SjYz
            dWs2Y0pwVzlXekNMdENjUVZVQlNEU0EK3BJ1DtVzsSyw6PvFMLEOMq5tP2CPz/NQ
            NO3FFXs20qbvyHgiv2T5nlMFsxvrArH2BmTommfR4kD+J1dQinRYsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY0JIWU12VExqZ0YvU3N1
            dDEvVkluTHQzL2FkU2VLTVd5ODIzb3BpV1ZNCmF4NktPc2R4Z05mN28zVHI0cHdJ
            WUMrazB0Y3Yyc2JxZUwxYVFSKzhuLzQKLS0tIGJsczRHSkc0WVg4bE9EWTg2NVdS
            WFZCaW5teHZxTjlueG14Z0xWV25xSXcKm9he2ArcwqddVhfoJFHh/cC0saVQVe2G
            onMv80lVVGGAHAr4O6hi8Dk09Vz2p0BmxS7ok6uaCNNNjSxviAiNXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxhkt6syw8mmfzzzgf9dtjkvt5j7au36nnsmv4vvuejdwmpv9ftssv9vkq
    lastmodified: "2026-09-06T14:10:27Z"
    mac: ENC[AES256_GCM,data:VRMugV8Owsqrfq1lo+9GVEQXjuJM+9Nn1GUukUMI7B/7XYc3kaJ4XRj61fd51gZ2g1B1p24mcV0g6b5ll+crmcFtxv51vEUpBbdY/Y7Ca4LoeyJfI6BkAB7AKNxgzQ+d9UgHS/iT1cyh8uZwRmem7tiY3pi3Il8drAmbSU34m90=,iv:1Ftf2AcSM9W4zst3TlwKpCHb304UchC+ygQamOWmzUU=,tag:cLkxwK7TOe+o0vD34qpuHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
