backup_caddy_restic_password: ENC[AES256_GCM,data:xvP7nUxyFe/f,iv:90eYHTiHLPrrvrMaK0aPSPtAJ2HXc1JPu6nF5BkB3dc=,tag:PbZlx2AeiULUSnedJuwhVA==,type:str]
backup_caddy_s3_access_key: ENC[AES256_GCM,data:o/0atYaVMgK8,iv:HorDc1kOb+Z+cgp4Xd5zhky4Z13eBlUvj45rDAXXCuI=,tag:ajlkxH1bnijz8oBKPtmuSw==,type:str]
backup_caddy_s3_secret_key: ENC[AES256_GCM,data:cUNWtLB4tClE,iv:gYKKPfFUXSf0I0Cz+uOjudt+qwTsffKC8oS1+og0qp0=,tag:7TpTOWDvQcozIthYzUsZWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRU1FbEtjenlhQjlicG9o
            U2VndTdHTFdqN1NrY3QyOXJLUDBlQ1RLaFd3CmJBSW9KMllBWFQ3R0hZR0x6Mlkr
            Q3ljN004aGlRQ3kwRWhLZEdWcE1Rd3MKLS0tIFZUVnYzMTdsV0lqQlZHL1o4SjYz
            dWs2Y0pwVzlXekNMdENjUVZVQlNEU0EK3BJ1DtVzsSyw6PvFMLEOMq5tP2CPz/NQ
            NO3FFXs20qbvyHgiv2T5nlMFsxvrArH2BmTommfR4kD+J1dQinRYsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ef6lafmvtk8myhsl28a79zz3463f6xupf8vxx5uduyptmtxmunq4v8nvm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY0JIWU12VExqZ0YvU3N1
            dDEvVkluTHQzL2FkU2VLTVd5ODIzb3BpV1ZNCmF4NktPc2R4Z05mN28zVHI0cHdJ
            WUMrazB0Y3Yyc2JxZUwxYVFSKzhuLzQKLS0tIGJsczRHSkc0WVg4bE9EWTg2NVdS
            WFZCaW5teHZxTjlueG14Z0xWV25xSXcKm9he2ArcwqddVhfoJFHh/cC0saVQVe2G
            onMv80lVVGGAHAr4O6hi8Dk09Vz2p0BmxS7ok6uaCNNNjSxviAiNXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxhkt6syw8mmfzzzgf9dtjkvt5j7au36nnsmv4vvuejdwmpv9ftssv9vkq
    lastmodified: "2026-09-06T13:55:01Z"
    mac: ENC[AES256_GCM,data:+PE+hhpltxaijH2A2W1P9kJwkIoOFzyFx4KMzzMGPoEYQyS1zK6J/ShB4hg1y0vJsTAm9lh9XoLEehe1uOq3kTsMYH0mtSOSulgEr2OPxYJQ/UWoGqdOCDBgqVp16NxXvIhuBa95/tA4visHLaJZk9a09g3HD9jal85f6hZFjLU=,iv:MGhonKqQw3j88HRjljPzQ26+evsHSAfOZyGWnAWyDPU=,tag:XkqH5zKSQqPJHEt3FdoFfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
